// Writes the per-page SEO head block into every HTML file, and regenerates
// sitemap.xml / robots.txt / llms.txt from the same single source of truth.
//
// Run it again after adding a page or changing a description:
//   node scripts/build-seo.mjs
//
// Everything is delimited by the SEO markers below, so re-running replaces the
// block rather than stacking duplicates.

import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// ── Change this one line if the site moves to a custom domain ───────────────
export const ORIGIN = 'https://vasojevich.com';

const AUTHOR = 'Mateja Vasojevikj';
// 1200x630 is the size link previews actually crop to. display.png is square
// and 1.6 MB, so it was both letterboxed and slow for scrapers to fetch.
const OG_IMAGE = `${ORIGIN}/misc/og-image.jpg`;
const OG_IMAGE_W = '1200';
const OG_IMAGE_H = '630';

const START = '<!-- SEO:START (generated by scripts/build-seo.mjs — edit there, not here) -->';
const END = '<!-- SEO:END -->';

/**
 * `changefreq` and `priority` are hints only; search engines largely ignore
 * them, but they cost nothing and some crawlers still read them.
 */
export const PAGES = [
  {
    file: 'index.html',
    path: '/',
    title: 'Mateja Vasojevikj — Photographer in Skopje | vasosofuji',
    description:
      'Concert, portrait and landscape photography by Mateja Vasojevikj (Vasojevich), known as vasosofuji, based in Skopje, North Macedonia. Open for bookings.',
    priority: '1.0',
    type: 'website',
  },
  {
    file: 'gallery.html',
    path: '/gallery.html',
    title: 'Photo Gallery — Portraits, Concerts, Landscapes | vasosofuji',
    description:
      'Browse photography by vasosofuji: portrait sessions, live concert coverage and landscapes from Skopje, Ohrid and across North Macedonia.',
    priority: '0.9',
  },
  {
    file: 'portraits.html',
    path: '/portraits.html',
    title: 'Portrait Photography in Skopje | vasosofuji',
    description:
      'Portrait photography by Mateja Vasojevikj in Skopje and Ohrid, North Macedonia. Shot on Fujifilm X-T2 and Canon 2000D. Book a session.',
    priority: '0.8',
  },
  {
    file: 'concerts.html',
    path: '/concerts.html',
    title: 'Concert & Live Music Photography in Skopje | vasosofuji',
    description:
      'Live music and concert photography from venues across Skopje — MKC, Laboratorium, Kotur and more. Gig coverage by vasosofuji.',
    priority: '0.8',
  },
  {
    file: 'landscapes.html',
    path: '/landscapes.html',
    title: 'Landscape Photography — Ohrid & North Macedonia | vasosofuji',
    description:
      'Landscape photography from Lake Ohrid, Vodno and around North Macedonia by Mateja Vasojevikj (vasosofuji).',
    priority: '0.7',
  },
  {
    file: 'videos.html',
    path: '/videos.html',
    title: 'Video & Cinematography Work | vasosofuji',
    description:
      'Short films, music videos and brand advertisements shot and edited by Mateja Vasojevikj in Skopje, North Macedonia.',
    priority: '0.7',
  },
  {
    file: 'about.html',
    path: '/about.html',
    title: 'About Mateja Vasojevikj — Photographer & Filmmaker, Skopje',
    description:
      'Mateja Vasojevikj — also written Vasojevich — is a photographer and cinematographer in Skopje, North Macedonia, working as vasosofuji. Gear, story and recent work.',
    priority: '0.6',
  },
  {
    file: 'collaborations.html',
    path: '/collaborations.html',
    title: 'Collaborations — Bands, Venues & Festivals | vasosofuji',
    description:
      'Artists, venues, festivals and organisations Mateja Vasojevikj has photographed and filmed with across North Macedonia.',
    priority: '0.6',
  },
  {
    file: 'webdev.html',
    path: '/webdev.html',
    title: 'Web Development & Motion Engineering | vasosofuji',
    description:
      'Bespoke web development and motion engineering by Mateja Vasojevikj — React, TypeScript and 60fps GSAP interaction, built in Skopje.',
    priority: '0.6',
  },
  {
    file: '404.html',
    path: '/404.html',
    title: 'Page not found | vasosofuji',
    description: 'That page does not exist. Head back to the gallery.',
    noindex: true,
  },
];

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// The markers contain regex metacharacters — "(", ")" and "." — so they must be
// escaped before going into a RegExp. Not escaping them is what made the
// re-run silently fail to match its own block.
const escRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// Person + local business. `alternateName` is where the spelling variants
// belong — Vasojevikj, Vasojevich and Васојевиќ are the same name transliterated
// three ways, and people search all three.
const personLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  '@id': `${ORIGIN}/#person`,
  name: 'Mateja Vasojevikj',
  alternateName: ['vasosofuji', 'Mateja Vasojevich', 'Матеја Васојевиќ'],
  url: `${ORIGIN}/`,
  image: OG_IMAGE,
  jobTitle: 'Photographer and Cinematographer',
  email: 'mailto:vasosofuji@gmail.com',
  address: {
    '@type': 'PostalAddress',
    addressLocality: 'Skopje',
    addressCountry: 'MK',
  },
  sameAs: [
    'https://instagram.com/vasosofuji',
    'https://www.linkedin.com/in/mateja-vasojevikj-907555290/',
    'https://www.flickr.com/photos/201695063@N02/',
  ],
};

const businessLd = {
  '@context': 'https://schema.org',
  '@type': 'ProfessionalService',
  '@id': `${ORIGIN}/#service`,
  name: 'vasosofuji — Photography & Cinematography',
  description:
    'Concert, portrait and landscape photography and video production in Skopje, North Macedonia.',
  url: `${ORIGIN}/`,
  image: OG_IMAGE,
  email: 'mailto:vasosofuji@gmail.com',
  founder: { '@id': `${ORIGIN}/#person` },
  areaServed: [
    { '@type': 'City', name: 'Skopje' },
    { '@type': 'City', name: 'Ohrid' },
    { '@type': 'Country', name: 'North Macedonia' },
  ],
  address: { '@type': 'PostalAddress', addressLocality: 'Skopje', addressCountry: 'MK' },
  knowsLanguage: ['en', 'mk'],
  sameAs: personLd.sameAs,
};

// The domain is vasojevich.com, so that spelling is a name in its own right.
// A WebSite entity lets search engines and answer engines resolve all of
// "vasosofuji", "Vasojevich" and "Vasojevikj" to the same site.
const siteLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  '@id': `${ORIGIN}/#website`,
  name: 'vasosofuji — Mateja Vasojevikj',
  alternateName: ['vasosofuji', 'Vasojevich', 'Mateja Vasojevich', 'Матеја Васојевиќ'],
  url: `${ORIGIN}/`,
  inLanguage: ['en', 'mk'],
  publisher: { '@id': `${ORIGIN}/#person` },
};

function galleryLd(page) {
  return {
    '@context': 'https://schema.org',
    '@type': 'ImageGallery',
    name: page.title,
    description: page.description,
    url: `${ORIGIN}${page.path}`,
    isPartOf: { '@type': 'WebSite', name: 'vasosofuji', url: `${ORIGIN}/` },
    author: { '@id': `${ORIGIN}/#person` },
  };
}

function headBlock(page) {
  const url = `${ORIGIN}${page.path === '/' ? '/' : page.path}`;
  const ld = [];
  if (page.file === 'index.html') ld.push(siteLd, personLd, businessLd);
  if (['gallery.html', 'portraits.html', 'concerts.html', 'landscapes.html'].includes(page.file)) {
    ld.push(galleryLd(page));
  }

  const lines = [
    START,
    `    <meta name="description" content="${esc(page.description)}">`,
    `    <meta name="author" content="${AUTHOR}">`,
    page.noindex
      ? '    <meta name="robots" content="noindex, follow">'
      : '    <meta name="robots" content="index, follow, max-image-preview:large">',
    `    <link rel="canonical" href="${url}">`,
    '',
    `    <meta property="og:type" content="${page.type || 'website'}">`,
    `    <meta property="og:site_name" content="vasosofuji">`,
    `    <meta property="og:title" content="${esc(page.title)}">`,
    `    <meta property="og:description" content="${esc(page.description)}">`,
    `    <meta property="og:url" content="${url}">`,
    `    <meta property="og:image" content="${OG_IMAGE}">`,
    `    <meta property="og:image:width" content="${OG_IMAGE_W}">`,
    `    <meta property="og:image:height" content="${OG_IMAGE_H}">`,
    `    <meta property="og:image:alt" content="${esc(AUTHOR)} — photographer, Skopje">`,
    `    <meta property="og:locale" content="en_US">`,
    `    <meta property="og:locale:alternate" content="mk_MK">`,
    '',
    `    <meta name="twitter:card" content="summary_large_image">`,
    `    <meta name="twitter:title" content="${esc(page.title)}">`,
    `    <meta name="twitter:description" content="${esc(page.description)}">`,
    `    <meta name="twitter:image" content="${OG_IMAGE}">`,
  ];

  for (const obj of ld) {
    lines.push('', `    <script type="application/ld+json">${JSON.stringify(obj)}</script>`);
  }
  lines.push(END);
  return lines.join('\n');
}

let touched = 0;
for (const page of PAGES) {
  const file = join(ROOT, page.file);
  let html;
  try {
    html = await readFile(file, 'utf8');
  } catch {
    console.warn(`skip ${page.file} (not found)`);
    continue;
  }

  // Title: one per page, replacing whatever is there.
  html = html.replace(/<title>[\s\S]*?<\/title>/i, `<title>${esc(page.title)}</title>`);

  // Remove any previously generated block FIRST. Doing it in this order keeps
  // the script idempotent: the strip below would otherwise gut the existing
  // block's own tags, and if the re-insert then failed the page would be left
  // with no description or canonical at all.
  html = html.replace(new RegExp(`\\n?${escRe(START)}[\\s\\S]*?${escRe(END)}`), '');

  // Drop any hand-written tags this block now owns, so nothing is declared twice.
  html = html
    .replace(/^[ \t]*<meta\s+name="description"[^>]*>\s*\n/gim, '')
    .replace(/^[ \t]*<meta\s+property="og:[^"]*"[^>]*>\s*\n/gim, '')
    .replace(/^[ \t]*<meta\s+name="twitter:[^"]*"[^>]*>\s*\n/gim, '')
    .replace(/^[ \t]*<link\s+rel="canonical"[^>]*>\s*\n/gim, '')
    .replace(/^[ \t]*<link\s+rel="image_src"[^>]*>\s*\n/gim, '');

  html = html.replace(/<\/title>/i, `</title>\n${headBlock(page)}`);

  await writeFile(file, html);
  touched++;
}

// ── sitemap.xml ────────────────────────────────────────────────────────────
const today = new Date().toISOString().slice(0, 10);
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${PAGES.filter((p) => !p.noindex)
  .map(
    (p) => `  <url>
    <loc>${ORIGIN}${p.path}</loc>
    <lastmod>${today}</lastmod>
    <priority>${p.priority}</priority>
  </url>`
  )
  .join('\n')}
</urlset>
`;
await writeFile(join(ROOT, 'sitemap.xml'), sitemap);

// ── robots.txt ─────────────────────────────────────────────────────────────
await writeFile(
  join(ROOT, 'robots.txt'),
  `User-agent: *
Allow: /

# Build output and source are not useful to crawlers
Disallow: /src/
Disallow: /node_modules/

Sitemap: ${ORIGIN}/sitemap.xml
`
);

console.log(`SEO block written to ${touched} page(s)`);
console.log('sitemap.xml and robots.txt regenerated');
console.log(`origin: ${ORIGIN}`);
